### ISSUE TITLE
Cygwin Issue

### ISSUE THREAD

**Issue by pedroalbanese** [dfateyev/libwhirlpool#1]
$ make
make  all-recursive
make[1]: Entrando no diretório '/cygdrive/h/PRGM/Linux/libwhirlpool-master'

Making all in src
make[2]: Entrando no diretório '/cygdrive/h/PRGM/Linux/libwhirlpool-master/src'

/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -static -MT Whirlpool.lo -MD -MP -MF .deps/Whirlpool.Tpo -c -o Whirlpool.lo Whirlpool.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -MT Whirlpool.lo -MD -MP -MF .deps/Whirlpool.Tpo -c Whirlpool.c -o Whirlpool.o
mv -f .deps/Whirlpool.Tpo .deps/Whirlpool.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -static -version-info 0:1:0  -o libwhirlpool.la -rpath /usr/local/lib Whirlpool.lo
libtool: link: warning: undefined symbols not allowed in i686-pc-cygwin shared libraries
libtool: link: ar cru .libs/libwhirlpool.a  Whirlpool.o
libtool: link: ranlib .libs/libwhirlpool.a
libtool: link: ( cd ".libs" && rm -f "libwhirlpool.la" && ln -s "../libwhirlpool.la" "libwhirlpool.la" )
gcc -DHAVE_CONFIG_H -I. -I..     -static -MT whirlpoolsum.o -MD -MP -MF .deps/whirlpoolsum.Tpo -c -o whirlpoolsum.o whirlpoolsum.c
mv -f .deps/whirlpoolsum.Tpo .deps/whirlpoolsum.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -static   -o whirlpoolsum.exe whirlpoolsum.o -lwhirlpool
libtool: link: gcc -o whirlpoolsum.exe whirlpoolsum.o  /cygdrive/h/PRGM/Linux/libwhirlpool-master/src/.libs/libwhirlpool.a
/usr/lib/gcc/i686-pc-cygwin/9.3.0/../../../../i686-pc-cygwin/bin/ld: /cygdrive/h/PRGM/Linux/libwhirlpool-master/src/.libs/libwhirlpool.a(Whirlpool.o):Whirlpool.c:(.text+0x3984): multiple definition of `main'; whirlpoolsum.o:whirlpoolsum.c:(.text+0xb42): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:453: whirlpoolsum.exe] Erro 1
make[2]: Saindo do diretório '/cygdrive/h/PRGM/Linux/libwhirlpool-master/src'

make[1]: *** [Makefile:385: all-recursive] Erro 1
make[1]: Saindo do diretório '/cygdrive/h/PRGM/Linux/libwhirlpool-master'

make: *** [Makefile:316: all] Erro 2

what's going wrong?

**Comment by dfateyev** [comment]
Fixed in 1.1 release
